"""
Standalone PINN for the inverse Störmer problem in cylindrical coordinates.

Identifies the magnetic coupling parameter alpha1 = q*M_z / (m*r0^3)
from observed trajectory data generated by the C Störmer-Verlet solvers.

Second-order formulation: the network outputs (rho, phi) directly.
ODE residuals use d²rho/dt_norm² via double autograd. No auxiliary
velocity variables (w_rho) — eliminates initialization problems.

M-free formulation: proton mass M cancels analytically from the force
and phi equations. All computations use c20_hat = c20/M, avoiding
tiny-number arithmetic (M ~ 1e-27).

Two modes:
  - "equatorial" (Z=0): 2 outputs (rho, phi), 2 ODE residuals
  - "3d": 3 outputs (rho, Z, phi), 3 ODE residuals

Reference: relatório PIBIC, Sections 3.3.1 (equatorial) and 3.3.2 (3D).
"""

import math
import torch
import torch.nn as nn
import numpy as np


class FourierFeatures(nn.Module):
    """Map scalar input to Fourier features: [t, sin(2*pi*f_i*t), cos(2*pi*f_i*t)]."""

    def __init__(self, n_frequencies=10):
        super().__init__()
        freqs = torch.linspace(1.0, float(n_frequencies), n_frequencies)
        self.register_buffer("freqs", freqs)
        self.output_dim = 1 + 2 * n_frequencies

    def forward(self, t):
        angles = 2 * math.pi * t * self.freqs
        return torch.cat([t, torch.sin(angles), torch.cos(angles)], dim=1)


class Stormer3DInversePINN(nn.Module):
    """Neural network with trainable alpha1 for the inverse Störmer problem.

    Second-order formulation:
      - equatorial: 2 outputs (rho, phi)
      - 3d: 3 outputs (rho, Z, phi)
    """

    def __init__(self, mode="equatorial", n_hidden=4, n_neurons=128,
                 n_frequencies=10, alpha1_init=5000.0):
        super().__init__()
        self.mode = mode
        self.fourier = FourierFeatures(n_frequencies=n_frequencies)
        input_dim = self.fourier.output_dim

        n_outputs = 2 if mode == "equatorial" else 3

        layers = [nn.Linear(input_dim, n_neurons), nn.Tanh()]
        for _ in range(n_hidden - 1):
            layers += [nn.Linear(n_neurons, n_neurons), nn.Tanh()]
        layers.append(nn.Linear(n_neurons, n_outputs))
        self.net = nn.Sequential(*layers)

        # Trainable alpha1 via exp: alpha1 = exp(log_alpha1) > 0
        self.log_alpha1 = nn.Parameter(
            torch.tensor(math.log(alpha1_init), dtype=torch.float64)
        )

        self._init_weights()

    def _init_weights(self):
        for m in self.net:
            if isinstance(m, nn.Linear):
                nn.init.xavier_normal_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, t_norm):
        features = self.fourier(t_norm)
        return self.net(features)

    def get_alpha1(self):
        """Return current alpha1 value (always positive via exp)."""
        return torch.exp(self.log_alpha1)


class Stormer3DInverseTrainer:
    """Handles loss computation for the inverse Störmer PINN.

    M-free formulation: all physics uses c20_hat = c20/M, so proton mass
    M never appears in the computation. This avoids numerical issues with
    M ~ 1e-27.

    Second-order: ODE residuals use d²rho/dt_norm² directly (no w_rho).
    """

    def __init__(self, model, dataset_path, device="cpu",
                 w_data=1.0, w_ode=1.0, w_energy=0.0,
                 obs_fraction=1.0, noise_std=0.0, seed=42):
        self.model = model.to(device)
        self.device = device
        self.mode = model.mode
        self.w_data = w_data
        self.w_ode = w_ode
        self.w_energy = w_energy

        # Load dataset
        data = np.load(dataset_path)
        self.M = float(data["M"])
        self.alpha1_true = float(data["alpha1_true"])

        # Known initial conditions
        self.rho0 = float(data["rho0"])
        self.drho0 = float(data["drho0"])
        self.phi0 = float(data["phi0"])
        self.dphi0 = float(data["dphi0"])

        if self.mode == "3d":
            self.Z0 = float(data["Z0"])
            self.dZ0 = float(data["dZ0"])

        self.T_obs = float(data["T_final"])
        self.T_obs2 = self.T_obs ** 2

        # --- Observation data: apply sparsity and noise ---
        t_obs_full = data["t_obs"]
        rho_obs_full = data["rho_obs"]
        phi_obs_full = data["phi_obs"]
        if self.mode == "3d":
            Z_obs_full = data["Z_obs"]

        rng = np.random.default_rng(seed)
        n_full = len(t_obs_full)

        if obs_fraction < 1.0:
            n_keep = max(2, int(n_full * obs_fraction))
            mid_indices = np.sort(
                rng.choice(np.arange(1, n_full - 1), n_keep - 2, replace=False)
            )
            indices = np.concatenate([[0], mid_indices, [n_full - 1]])
        else:
            indices = np.arange(n_full)

        t_obs = t_obs_full[indices]
        rho_obs = rho_obs_full[indices].copy()
        phi_obs = phi_obs_full[indices].copy()

        if noise_std > 0:
            rho_obs += rng.normal(0, noise_std, len(rho_obs))
            phi_obs += rng.normal(0, noise_std, len(phi_obs))

        t_obs_norm = t_obs / self.T_obs

        self.t_obs_norm = torch.tensor(
            t_obs_norm, dtype=torch.float64, device=device
        ).unsqueeze(1)
        self.rho_obs = torch.tensor(
            rho_obs, dtype=torch.float64, device=device
        )
        self.phi_obs = torch.tensor(
            phi_obs, dtype=torch.float64, device=device
        )

        if self.mode == "3d":
            Z_obs = Z_obs_full[indices].copy()
            if noise_std > 0:
                Z_obs += rng.normal(0, noise_std, len(Z_obs))
            self.Z_obs = torch.tensor(
                Z_obs, dtype=torch.float64, device=device
            )

        # --- Collocation points ---
        t_coll = data["t_collocation"]
        t_coll_norm = t_coll / self.T_obs
        self.t_coll_norm = torch.tensor(
            t_coll_norm, dtype=torch.float64, device=device
        ).unsqueeze(1).requires_grad_(True)

        # --- Reference data (for plotting only) ---
        self.t_ref = data["t_ref"]
        self.rho_ref = data["rho_ref"]
        self.phi_ref = data["phi_ref"]
        if self.mode == "3d":
            self.Z_ref = data["Z_ref"]

        # --- Compute ODE normalization scales at initial alpha1 ---
        # These make ODE residuals O(1), so w_ode is meaningful.
        a1_init = model.get_alpha1().item()
        c_hat_init = self.rho0**2 * self.dphi0 + a1_init / self.rho0
        force_ref = abs(c_hat_init**2 / self.rho0**3
                        - 3 * a1_init * c_hat_init / self.rho0**4
                        + 2 * a1_init**2 / self.rho0**5)
        phi_rate_ref = abs(c_hat_init / self.rho0**2 - a1_init / self.rho0**3)

        self.scale_rho = max(self.T_obs2 * force_ref, 1.0)
        self.scale_phi = max(self.T_obs * phi_rate_ref, 1.0)

        print(f"  Mode: {self.mode}")
        print(f"  Observations: {len(t_obs)} points "
              f"(fraction={obs_fraction}, noise_std={noise_std})")
        print(f"  Collocation: {len(t_coll)} points")
        print(f"  T_obs = {self.T_obs:.2f}")
        print(f"  ODE scales: rho={self.scale_rho:.2f}, phi={self.scale_phi:.2f}")
        print(f"  alpha1_true = {self.alpha1_true}, "
              f"alpha1_init = {model.get_alpha1().item():.4f}")

    def _c20_hat(self, alpha1):
        """M-free angular momentum: c20_hat = c20/M.

        Equatorial: c20_hat = rho0^2 * dphi0 + alpha1 / rho0
        3D: c20_hat = rho0^2 * dphi0 + alpha1 * rho0^2 / R0^3
        """
        if self.mode == "equatorial":
            return self.rho0**2 * self.dphi0 + alpha1 / self.rho0
        else:
            R0 = math.sqrt(self.rho0**2 + self.Z0**2)
            return self.rho0**2 * self.dphi0 + alpha1 * self.rho0**2 / R0**3

    def loss_data(self):
        """Data loss: MSE between predictions and observations."""
        out = self.model(self.t_obs_norm)

        if self.mode == "equatorial":
            rho_pred = out[:, 0]
            phi_pred = out[:, 1]
            return torch.mean((rho_pred - self.rho_obs)**2
                              + (phi_pred - self.phi_obs)**2)
        else:
            rho_pred = out[:, 0]
            Z_pred = out[:, 1]
            phi_pred = out[:, 2]
            return torch.mean((rho_pred - self.rho_obs)**2
                              + (Z_pred - self.Z_obs)**2
                              + (phi_pred - self.phi_obs)**2)

    def loss_ode(self):
        """ODE residual loss — second-order, M-free formulation.

        Equatorial (2 residuals):
          r_rho = d²rho/dt_norm² - T_obs² * [c_hat²/rho³ - 3*a1*c_hat/rho⁴ + 2*a1²/rho⁵]
          r_phi = dphi/dt_norm   - T_obs  * [c_hat/rho² - a1/rho³]

        3D (3 residuals):
          r_rho = d²rho/dt_norm² - T_obs² * [c_hat²/rho³ + 3*a1²*rho³/R⁸ - a1²*rho/R⁶ - 3*a1*c_hat*rho/(R⁵)]
          r_Z   = d²Z/dt_norm²   - T_obs² * [3*a1²*rho²*Z/R⁸ - 3*a1*c_hat*Z/(R⁵)]
          r_phi = dphi/dt_norm   - T_obs  * [c_hat/rho² - a1/R³]
        """
        alpha1 = self.model.get_alpha1()
        c_hat = self._c20_hat(alpha1)
        t = self.t_coll_norm

        out = self.model(t)

        if self.mode == "equatorial":
            rho = out[:, 0:1]
            phi = out[:, 1:2]

            ones = torch.ones_like(rho)

            # First derivatives
            drho_dt = torch.autograd.grad(
                rho, t, ones, create_graph=True, retain_graph=True)[0]
            dphi_dt = torch.autograd.grad(
                phi, t, ones, create_graph=True, retain_graph=True)[0]

            # Second derivative of rho
            d2rho_dt2 = torch.autograd.grad(
                drho_dt, t, ones, create_graph=True, retain_graph=True)[0]

            # Force (M-free): ddot_rho = c_hat²/rho³ - 3*a1*c_hat/rho⁴ + 2*a1²/rho⁵
            force_rho = (c_hat**2 / rho**3
                         - 3 * alpha1 * c_hat / rho**4
                         + 2 * alpha1**2 / rho**5)

            # Phi rate (M-free): dphi/dt = c_hat/rho² - a1/rho³
            phi_rate = c_hat / rho**2 - alpha1 / rho**3

            r_rho = (d2rho_dt2 - self.T_obs2 * force_rho) / self.scale_rho
            r_phi = (dphi_dt - self.T_obs * phi_rate) / self.scale_phi

            return torch.mean(r_rho**2 + r_phi**2)

        else:
            rho = out[:, 0:1]
            Z = out[:, 1:2]
            phi = out[:, 2:3]

            ones = torch.ones_like(rho)
            R = torch.sqrt(rho**2 + Z**2)

            # First derivatives
            drho_dt = torch.autograd.grad(
                rho, t, ones, create_graph=True, retain_graph=True)[0]
            dZ_dt = torch.autograd.grad(
                Z, t, ones, create_graph=True, retain_graph=True)[0]
            dphi_dt = torch.autograd.grad(
                phi, t, ones, create_graph=True, retain_graph=True)[0]

            # Second derivatives
            d2rho_dt2 = torch.autograd.grad(
                drho_dt, t, ones, create_graph=True, retain_graph=True)[0]
            d2Z_dt2 = torch.autograd.grad(
                dZ_dt, t, ones, create_graph=True, retain_graph=True)[0]

            # Forces (M-free)
            force_rho = (c_hat**2 / rho**3
                         + 3 * alpha1**2 * rho**3 / R**8
                         - alpha1**2 * rho / R**6
                         - 3 * alpha1 * c_hat * rho / R**5)
            force_Z = (3 * alpha1**2 * rho**2 * Z / R**8
                       - 3 * alpha1 * c_hat * Z / R**5)

            phi_rate = c_hat / rho**2 - alpha1 / R**3

            r_rho = (d2rho_dt2 - self.T_obs2 * force_rho) / self.scale_rho
            r_Z = (d2Z_dt2 - self.T_obs2 * force_Z) / self.scale_rho
            r_phi = (dphi_dt - self.T_obs * phi_rate) / self.scale_phi

            return torch.mean(r_rho**2 + r_Z**2 + r_phi**2)

    def total_loss(self):
        """Compute total weighted loss."""
        l_data = self.loss_data()
        l_ode = self.loss_ode()

        total = self.w_data * l_data + self.w_ode * l_ode
        return total, l_data, l_ode

    def predict(self, t_physical):
        """Predict trajectory given physical time array."""
        self.model.eval()
        t_norm = torch.tensor(
            t_physical / self.T_obs, dtype=torch.float64, device=self.device
        ).unsqueeze(1)
        with torch.no_grad():
            out = self.model(t_norm)

        if self.mode == "equatorial":
            return {"rho": out[:, 0].cpu().numpy(),
                    "phi": out[:, 1].cpu().numpy()}
        else:
            return {"rho": out[:, 0].cpu().numpy(),
                    "Z": out[:, 1].cpu().numpy(),
                    "phi": out[:, 2].cpu().numpy()}

    def get_alpha1_error(self):
        """Return (alpha1_estimated, alpha1_true, relative_error)."""
        alpha1_est = self.model.get_alpha1().item()
        rel_err = abs(alpha1_est - self.alpha1_true) / self.alpha1_true
        return alpha1_est, self.alpha1_true, rel_err
